# Generated by Django 4.0.3 on 2022-04-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='artist',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.biography'),
            preserve_default=False,
        ),
    ]
