# Generated by Django 4.0.3 on 2022-04-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rating_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Biography',
        ),
    ]
